# syntax = docker/dockerfile:1.4.3

FROM ghcr.io/graalvm/native-image:muslib-ol9-java17-22.3.0 AS compile

RUN microdnf install -y findutils

WORKDIR /build
COPY --link . /build/
ENV GRADLE_USER_HOME=".gradle-cache" JAVA_TOOL_OPTIONS="-Djdk.lang.Process.launchMechanism=vfork"
RUN --mount=type=cache,target=.gradle-cache ./gradlew --no-daemon nativeCompile


# shrink app
FROM --platform=${BUILDPLATFORM} alpine:3.16 AS builder

WORKDIR /build
RUN --mount=type=cache,target=/etc/apk/cache apk --update-cache add tzdata
RUN adduser \
    --disabled-password \
    --gecos "" \
    --home "/nonexistent" \
    --shell "/sbin/nologin" \
    --no-create-home \
    --uid "10001" \
    "notes"


# create image with all required files for squashing in later stage
FROM scratch AS squash

COPY --link --from=alpine:3.16 --chown=10001:10001 --chmod=1777 /tmp /tmp
COPY --link --from=builder /usr/share/zoneinfo/ /usr/share/zoneinfo/
COPY --link --from=builder /etc/hosts /etc/group /etc/passwd /etc/ssl/ /etc/
COPY --link --from=compile --chown=10001:10001 --chmod=500 /build/build/native/nativeCompile/notes /app/notes


# final image
FROM scratch

ENV TZ=Europe/Berlin SSL_CERT_DIR=/etc/ssl/certs PATH=/app
USER 10001:10001
COPY --link --from=squash / /
WORKDIR /app

ENTRYPOINT ["/app/notes"]
