# syntax = docker/dockerfile:1.4.3

FROM ghcr.io/graalvm/native-image:muslib-ol9-java17-22.3.0 AS builder

RUN microdnf update -y \
 && microdnf install --nodocs -y tar gzip findutils \
 && microdnf clean all \
 && rm -rf /var/cache/yum
WORKDIR /build
ENV GRADLE_OPTS="-Dorg.gradle.project.buildDir=/gradle/build" \
    GRADLE_USER_HOME="/gradle/home" \
    PROJECT_CACHE_DIR="/gradle/project-cache-dir"
RUN --mount=type=cache,target=$GRADLE_USER_HOME --mount=type=cache,target=$PROJECT_CACHE_DIR --mount=source=.,target=. \
    ./gradlew --no-watch-fs --no-daemon --project-cache-dir $PROJECT_CACHE_DIR -Pstatic nativeCompile
RUN strip --strip-all /gradle/build/native/nativeCompile/notes


# final image
FROM gcr.io/distroless/static:nonroot

USER 65532:65532
WORKDIR /home/nonroot
EXPOSE 8080 8090
ENTRYPOINT ["/home/nonroot/etaGuard"]
COPY --link --from=builder --chown=10001:10001 --chmod=600 /tmp /home/nonroot/database
COPY --link --from=builder --chown=10001:10001 --chmod=500 /gradle/build/native/nativeCompile/notes /home/nonroot/notes
